### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [infinit/elle#3]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Reachability](https://github.com/infinit/elle/blob/45197071d0d31e337685a29b473c70d7a835b6dc/reactor/src/reactor/network/reachability.cc#L293 "Destructor for Reachability")
- [reactor_pthread_mutex_destroy](https://github.com/infinit/elle/blob/45197071d0d31e337685a29b473c70d7a835b6dc/reactor/src/reactor/pthread.cc#L32 "reactor_pthread_mutex_destroy function")

**Comment by Dimrok** [comment]
Right! Thanks for noticing this.

Elle is currently being revamped. I'll integrate that change and push it in the days to come.

**Comment by Dimrok** [comment]
Fixed (b0eecc52a04a2c927e358976da18821e7218a94c).

Thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/infinit/elle/commit/b0eecc52a04a2c927e358976da18821e7218a94c "Remove unnecessary null pointer checks or avoid using naked pointers.").
