### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by Tauril** [infinit/elle#6]
In the `.gitmodules` file, the path for the drake dependency is `../drake`. Shouldn't it be the path towards your drake's fork repository on github?

Same for `miniupnp`, `libutp` and `dokan`.

**Comment by Dimrok** [comment]
Hi @Tauril.

We use relative git submodules because we have our own CI (on GitLab). With this trick, we can have both GitLab and GitHub that live side-by-side until our full migration to GitHub.

**Comment by Dimrok** [comment]
Ok, I understand your problem... The forks don't work in this configuration.

**Comment by mefyl** [comment]
Elle now uses subtrees, so this is not an issue anymore.
