### ISSUE TITLE
failed to build with gcc 7.3.0

### ISSUE THREAD

**Issue by iozy** [infinit/elle#8]
Unable to build with fresh version of g++ compiler:

`g++ -v`
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-11ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-11ubuntu1) 

errors look like:
In file included from ../../src/elle/reactor/Channel.hh:163:0,
                 from ../../src/elle/reactor/Generator.hh:5,
                 from ../../src/elle/reactor/Generator.cc:1:
../../src/elle/reactor/Channel.hxx: In member function ‘const T& elle::reactor::Channel<T, Container>::peek() const’:
../../src/elle/reactor/Channel.hxx:193:42: error: no matching function for call to ‘wait(const elle::reactor::Barrier&)’
         reactor::wait(this->_read_barrier);
                                          ^
In file included from ../../src/elle/reactor/Channel.hxx:3:0,
                 from ../../src/elle/reactor/Channel.hh:163,
                 from ../../src/elle/reactor/Generator.hh:5,
                 from ../../src/elle/reactor/Generator.cc:1:
../../src/elle/reactor/scheduler.hh:332:5: note: candidate: bool elle::reactor::wait(elle::reactor::Waitable&, elle::DurationOpt) <near match>
     wait(Waitable& waitable, DurationOpt timeout = {});
     ^~~~
../../src/elle/reactor/scheduler.hh:332:5: note:   conversion of argument 1 would be ill-formed:
../../src/elle/reactor/scheduler.hh:335:5: note: candidate: bool elle::reactor::wait(const Waitables&, elle::DurationOpt)
     wait(Waitables const& waitables, DurationOpt timeout = {});
     ^~~~
../../src/elle/reactor/scheduler.hh:335:5: note:   no known conversion for argument 1 from ‘const elle::reactor::Barrier’ to ‘const Waitables& {aka const std::vector<elle::reactor::Waitable*>&}’
../../src/elle/reactor/scheduler.hh:338:5: note: candidate: bool elle::reactor::wait(const std::vector<std::reference_wrapper<elle::reactor::Waitable> >&, elle::DurationOpt)
     wait(std::vector<std::reference_wrapper<Waitable>> const& waitables,
     ^~~~
../../src/elle/reactor/scheduler.hh:338:5: note:   no known conversion for argument 1 from ‘const elle::reactor::Barrier’ to ‘const std::vector<std::reference_wrapper<elle::reactor::Waitable> >&’
../../src/elle/reactor/scheduler.hh:342:5: note: candidate: void elle::reactor::wait(boost::signals2::signal<void()>&)
     wait(boost::signals2::signal<void ()>& signal);
     ^~~~
../../src/elle/reactor/scheduler.hh:342:5: note:   no known conversion for argument 1 from ‘const elle::reactor::Barrier’ to ‘boost::signals2::signal<void()>&’
In file included from ../../src/elle/reactor/scheduler.hh:379:0,
                 from ../../src/elle/reactor/Channel.hxx:3,
                 from ../../src/elle/reactor/Channel.hh:163,
                 from ../../src/elle/reactor/Generator.hh:5,
                 from ../../src/elle/reactor/Generator.cc:1:
../../src/elle/reactor/scheduler.hxx:122:5: note: candidate: template<class Prototype, class ... Args> void elle::reactor::wait(boost::signals2::signal<Prototype>&, Args&& ...)
     wait(boost::signals2::signal<Prototype>& signal, Args&& ... args)
     ^~~~
../../src/elle/reactor/scheduler.hxx:122:5: note:   template argument deduction/substitution failed:
In file included from ../../src/elle/reactor/Channel.hh:163:0,
                 from ../../src/elle/reactor/Generator.hh:5,
                 from ../../src/elle/reactor/Generator.cc:1:
../../src/elle/reactor/Channel.hxx:193:42: note:   types ‘boost::signals2::signal<Prototype>’ and ‘const elle::reactor::Barrier’ have incompatible cv-qualifiers
         reactor::wait(this->_read_barrier);
                                          ^
and lots of warnings like:
In file included from ../../src/elle/serialization.hh:4:0,
                 from ../../src/elle/Exception.hh:9,
                 from ../../src/elle/Error.hh:3,
                 from ../../src/elle/cryptography/Error.hh:3,
                 from ../../src/elle/cryptography/dsa/PrivateKey.cc:9:
../../src/elle/Version.hh:75:13: warning: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>.
     ELLE_ATTRIBUTE_R(uint8_t, minor);
             ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mefyl** [comment]
Fixed a while ago.
